### ISSUE TITLE
Parameter Review

### ISSUE THREAD

**Issue by k-florek** [StaPH-B/titan#1]
A review of each task in the Titan Illumina PE workflow is needed [(Titan WDL)](https://github.com/StaPH-B/public_health_viral_genomics/blob/main/workflows/wf_titan_illumina_pe.wdl). Ideally, each task will be reviewed by 2 people with a focus on the parameter settings to ensure that the parameters are set appropriately and make sense for the broader application of this workflow.

Please perform the following for each Task:

* Examine the docker container is correct with correct version
* Examine the correct application command is used
* Examine the parameters used for each application
  * Make a note or update any hard coded parameters or flags that will need to be added to the configuration
  * Make a note or update the code for any missing parameters that need to be added

Please comment here with the task you reviewed and perform a pull request on any updates or changes to the code.

**Comment by kevinlibuit** [comment]
Task updates we've made on the Theiagen repo: 
- [Swapped seqyclean out for Trimmomatic & bbDuk for read cleaning and adapter/phix removal](https://github.com/theiagen/public_health_viral_genomics/commit/61c5f6070672ca3a134ce21dd42390481a20cd82)
- [Updated percent coverage to reflect coverage of ATCG/len(reference) ](https://github.com/theiagen/public_health_viral_genomics/commit/3a5208f70316699da0a789d29f2f0d4a0130e9b9)
- Updated output names (various commits)

**Comment by kevinlibuit** [comment]
Updated VADR task to most resent stable tag (1.2)
- [Required some command-level changes in addition to updated docker tag](https://github.com/theiagen/public_health_viral_genomics/blob/main/tasks/task_ncbi.wdl#L786)

*edit: formatting
