### ISSUE TITLE
Bedtools Container Update

### ISSUE THREAD

**Issue by jvhagey** [StaPH-B/titan#11]
In [task_amplicon_metrics.wdl](https://github.com/StaPH-B/public_health_viral_genomics/blob/main/tasks/task_amplicon_metrics.wdl) both tasks pull  `staphb/ivar:1.2.2_artic20200528` (contains bedtools v2.26.0), but these tasks just use `bedtools`.  I suggest that we pull `staphb/bedtools:2.30.0` so there is a quick way to see what version of bedtools is being used in this task.

**Comment by k-florek** [comment]
I updated both tasks to use staphb/bedtools:2.30.0 in pull request #12
