### ISSUE TITLE
Titan PE human read removal step

### ISSUE THREAD

**Issue by k-florek** [StaPH-B/titan#3]
Inclusion of a Task to remove human reads is needed to prepare fastq files for upload into SRA. The ideal choice is to use the [NCBI SRA Human Scrubber](https://github.com/ncbi/sra-human-scrubber) tool.

Process for this issues should be:
* Pick the approach/tool to be used
  * [NCBI SRA Human Scrubber](https://github.com/ncbi/sra-human-scrubber) makes the most sense but is still in "testing"
* Containerization (Docker) of tool and added to StaPH-B/docker-builds
  * Optionally use an already built container
* Develop WDL task and include in Titan PE workflow
  * Raw fastq reads should still have fastqc performed
  * Reads with human reads removed should be used for all downstream steps in Titan PE

**Comment by kevinlibuit** [comment]
Issue in [NCBI scrubber identified](https://github.com/ncbi/sra-human-scrubber/issues/3); output incompatible with downstream tasks

*edit hyperlink

**Comment by kevinlibuit** [comment]
Issue with the NCBI Scrubber identified and addressed in latest docker release: ncbi/sra-human-scrubber:1.0.2021-04-19
We incorporated the updated tool into a [two tasks (pe/se)](https://github.com/theiagen/public_health_viral_genomics/blob/main/tasks/task_read_clean.wdl#L3) and incorporated these into our Titan Illumina PE, ONT, and ClearLabs workflows--the scrubber is not yet compatible with short-read data expected for the Titan Illumina SE workflow.

**Comment by kevinlibuit** [comment]
Issue closed in Theiagen repo with latest PR: https://github.com/theiagen/public_health_viral_genomics/pull/10
