### ISSUE TITLE
Switch task code blocks from {} to <<< >>>

### ISSUE THREAD

**Issue by k-florek** [StaPH-B/titan#4]
This allows for easier usage of interpolating variables in bash script syntax.

**Comment by jvhagey** [comment]
Just to add some more details:

Switch from `{}` to `<<<>>>` syntax in the command section of both `tasks` and `workflows` to avoid bash issues. See the [wdl documentation](https://github.com/openwdl/wdl/blob/main/versions/1.0/SPEC.md#command-section) for more details.  

Bash variables should have `${variable}` syntax while other wdl variables should use `~{variable}` syntax. 

Comment to confirm which tasks and workflows have been checked. Priority should be on [titan_illumina_pe.wdl](https://github.com/StaPH-B/public_health_viral_genomics/blob/main/workflows/wf_titan_illumina_pe.wdl)
