### ISSUE TITLE
Switch from SeqyClean to Trimmomatic/bbduk

### ISSUE THREAD

**Issue by jvhagey** [StaPH-B/titan#5]
- [x] Remove seqyclean task from [wf_read_QC_trim.wdl](https://github.com/StaPH-B/public_health_viral_genomics/blob/main/workflows/wf_read_QC_trim.wdl)
- [x] Implement changes @kevinlibuit has made with Theiagen's workflow [mentioned](https://github.com/StaPH-B/public_health_viral_genomics/issues/1#issuecomment-812604342), by creating a new task that contains Trimmomatic and bbduk steps.
- [x] Add code to call these tasks in [wf_read_QC_trim.wdl](https://github.com/StaPH-B/public_health_viral_genomics/blob/main/workflows/wf_read_QC_trim.wdl)

**Comment by k-florek** [comment]
I've addressed this points in Pull Request #12 please let me know if I have missed anything.
