### ISSUE TITLE
VADR Task update

### ISSUE THREAD

**Issue by jvhagey** [StaPH-B/titan#8]
Update the [task_ncbi.wdl](https://github.com/StaPH-B/public_health_viral_genomics/blob/main/tasks/task_ncbi.wdl) with the following:

- [x] update container from `staph/vadr:1.1.2` to `staphb/vadr:1.2`
- [x] add [fasta-trim-terminal-ambigs.pl](https://github.com/ncbi/vadr/wiki/Coronavirus-annotation#howto) 

These steps have been implemented in [Theiagen's workflow](https://github.com/theiagen/public_health_viral_genomics/blob/main/tasks/task_ncbi.wdl#L786) as outlined by @kevinlibuit in another [issue](https://github.com/StaPH-B/public_health_viral_genomics/issues/1#issuecomment-822537002).

**Comment by k-florek** [comment]
This has been addressed in pull request #12
