### ISSUE TITLE
Nextclade Container Updates

### ISSUE THREAD

**Issue by jvhagey** [StaPH-B/titan#9]
Within the [task_taxonID.wdl](https://github.com/StaPH-B/public_health_viral_genomics/blob/main/tasks/task_taxonID.wdl) the task nextclade_one_sample is pulling `neherlab/nextclade:latest` which might change over time. Consider changing to most [recent one](https://hub.docker.com/r/neherlab/nextclade/tags?page=1&ordering=last_updated), which is currently `neherlab/nextclade:0.14.2-alpine3.12`. Or it could be changed to a user input like Pangolin is.

**Comment by k-florek** [comment]
I think changing to user input would make the most sense.

**Comment by k-florek** [comment]
I updated the container to point to neherlab/nextclade:0.14.2 with pull request #12 
This is now a parameter and can be changed at runtime.
